apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenuitest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenuitest
  template:
    metadata:
      labels:
        app: mavenuitest
    spec:
      containers:
        - name: mavenuitest
          image: punnamradhikareddy/dockerkubernetesdeployment1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenuitest
spec:
  selector:
    app: mavenuitest
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
